### ISSUE TITLE
Remove rustfmt settings from ci.sh

### ISSUE THREAD

**Issue by ubnt-intrepid** [pikkr/pikkr#46]
The installation process of rustfmt makes the total time of CI test huge.
IMO, applying the code formatter should be done before commiting, not in CI.

**Comment by kjmrknsn** [comment]
Travis CI does not install rustfmt again because of its caching feature: https://github.com/pikkr/pikkr/blob/bcbccbf32d6f0169a50786933cdbadd9ed70747b/.travis.yml#L9

https://github.com/pikkr/pikkr/blob/2814034f8c884cce0887c96d10269598bef5e657/ci.sh#L10 is executed so that CI fails when the source code is not formatted by rustfmt.

**Comment by ubnt-intrepid** [comment]
I'd understood the purpose...
Thank you for your comment.
